// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package gmailapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// GmailapiSvcClient is the client API for GmailapiSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GmailapiSvcClient interface {
	SubscribeToMail(ctx context.Context, in *SubscriptionRequest, opts ...grpc.CallOption) (*SubscriptionResponse, error)
	OpenOTCOrder(ctx context.Context, in *OTCOrderRequest, opts ...grpc.CallOption) (*OTCOrderResponse, error)
	GetConfirmationDetails(ctx context.Context, in *OTCOrderResponse, opts ...grpc.CallOption) (*ConfirmationResponse, error)
	GetClientSentiment(ctx context.Context, in *ClientSentimentRequest, opts ...grpc.CallOption) (*ClientSentimentResponse, error)
	OpenLightStreamerSubscription(ctx context.Context, in *LightStreamerSubRequest, opts ...grpc.CallOption) (GmailapiSvc_OpenLightStreamerSubscriptionClient, error)
	MarketSearch(ctx context.Context, in *ClientSentimentRequest, opts ...grpc.CallOption) (*MarketSearchResponse, error)
}

type gmailapiSvcClient struct {
	cc grpc.ClientConnInterface
}

func NewGmailapiSvcClient(cc grpc.ClientConnInterface) GmailapiSvcClient {
	return &gmailapiSvcClient{cc}
}

func (c *gmailapiSvcClient) SubscribeToMail(ctx context.Context, in *SubscriptionRequest, opts ...grpc.CallOption) (*SubscriptionResponse, error) {
	out := new(SubscriptionResponse)
	err := c.cc.Invoke(ctx, "/gmailapi.GmailapiSvc/subscribeToMail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gmailapiSvcClient) OpenOTCOrder(ctx context.Context, in *OTCOrderRequest, opts ...grpc.CallOption) (*OTCOrderResponse, error) {
	out := new(OTCOrderResponse)
	err := c.cc.Invoke(ctx, "/gmailapi.GmailapiSvc/openOTCOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gmailapiSvcClient) GetConfirmationDetails(ctx context.Context, in *OTCOrderResponse, opts ...grpc.CallOption) (*ConfirmationResponse, error) {
	out := new(ConfirmationResponse)
	err := c.cc.Invoke(ctx, "/gmailapi.GmailapiSvc/getConfirmationDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gmailapiSvcClient) GetClientSentiment(ctx context.Context, in *ClientSentimentRequest, opts ...grpc.CallOption) (*ClientSentimentResponse, error) {
	out := new(ClientSentimentResponse)
	err := c.cc.Invoke(ctx, "/gmailapi.GmailapiSvc/getClientSentiment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gmailapiSvcClient) OpenLightStreamerSubscription(ctx context.Context, in *LightStreamerSubRequest, opts ...grpc.CallOption) (GmailapiSvc_OpenLightStreamerSubscriptionClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GmailapiSvc_serviceDesc.Streams[0], "/gmailapi.GmailapiSvc/openLightStreamerSubscription", opts...)
	if err != nil {
		return nil, err
	}
	x := &gmailapiSvcOpenLightStreamerSubscriptionClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GmailapiSvc_OpenLightStreamerSubscriptionClient interface {
	Recv() (*LightStreamerSubResponse, error)
	grpc.ClientStream
}

type gmailapiSvcOpenLightStreamerSubscriptionClient struct {
	grpc.ClientStream
}

func (x *gmailapiSvcOpenLightStreamerSubscriptionClient) Recv() (*LightStreamerSubResponse, error) {
	m := new(LightStreamerSubResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gmailapiSvcClient) MarketSearch(ctx context.Context, in *ClientSentimentRequest, opts ...grpc.CallOption) (*MarketSearchResponse, error) {
	out := new(MarketSearchResponse)
	err := c.cc.Invoke(ctx, "/gmailapi.GmailapiSvc/marketSearch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GmailapiSvcServer is the server API for GmailapiSvc service.
// All implementations must embed UnimplementedGmailapiSvcServer
// for forward compatibility
type GmailapiSvcServer interface {
	SubscribeToMail(context.Context, *SubscriptionRequest) (*SubscriptionResponse, error)
	OpenOTCOrder(context.Context, *OTCOrderRequest) (*OTCOrderResponse, error)
	GetConfirmationDetails(context.Context, *OTCOrderResponse) (*ConfirmationResponse, error)
	GetClientSentiment(context.Context, *ClientSentimentRequest) (*ClientSentimentResponse, error)
	OpenLightStreamerSubscription(*LightStreamerSubRequest, GmailapiSvc_OpenLightStreamerSubscriptionServer) error
	MarketSearch(context.Context, *ClientSentimentRequest) (*MarketSearchResponse, error)
	mustEmbedUnimplementedGmailapiSvcServer()
}

// UnimplementedGmailapiSvcServer must be embedded to have forward compatible implementations.
type UnimplementedGmailapiSvcServer struct {
}

func (UnimplementedGmailapiSvcServer) SubscribeToMail(context.Context, *SubscriptionRequest) (*SubscriptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubscribeToMail not implemented")
}
func (UnimplementedGmailapiSvcServer) OpenOTCOrder(context.Context, *OTCOrderRequest) (*OTCOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenOTCOrder not implemented")
}
func (UnimplementedGmailapiSvcServer) GetConfirmationDetails(context.Context, *OTCOrderResponse) (*ConfirmationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfirmationDetails not implemented")
}
func (UnimplementedGmailapiSvcServer) GetClientSentiment(context.Context, *ClientSentimentRequest) (*ClientSentimentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClientSentiment not implemented")
}
func (UnimplementedGmailapiSvcServer) OpenLightStreamerSubscription(*LightStreamerSubRequest, GmailapiSvc_OpenLightStreamerSubscriptionServer) error {
	return status.Errorf(codes.Unimplemented, "method OpenLightStreamerSubscription not implemented")
}
func (UnimplementedGmailapiSvcServer) MarketSearch(context.Context, *ClientSentimentRequest) (*MarketSearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarketSearch not implemented")
}
func (UnimplementedGmailapiSvcServer) mustEmbedUnimplementedGmailapiSvcServer() {}

// UnsafeGmailapiSvcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GmailapiSvcServer will
// result in compilation errors.
type UnsafeGmailapiSvcServer interface {
	mustEmbedUnimplementedGmailapiSvcServer()
}

func RegisterGmailapiSvcServer(s grpc.ServiceRegistrar, srv GmailapiSvcServer) {
	s.RegisterService(&_GmailapiSvc_serviceDesc, srv)
}

func _GmailapiSvc_SubscribeToMail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GmailapiSvcServer).SubscribeToMail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gmailapi.GmailapiSvc/subscribeToMail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GmailapiSvcServer).SubscribeToMail(ctx, req.(*SubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GmailapiSvc_OpenOTCOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OTCOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GmailapiSvcServer).OpenOTCOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gmailapi.GmailapiSvc/openOTCOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GmailapiSvcServer).OpenOTCOrder(ctx, req.(*OTCOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GmailapiSvc_GetConfirmationDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OTCOrderResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GmailapiSvcServer).GetConfirmationDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gmailapi.GmailapiSvc/getConfirmationDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GmailapiSvcServer).GetConfirmationDetails(ctx, req.(*OTCOrderResponse))
	}
	return interceptor(ctx, in, info, handler)
}

func _GmailapiSvc_GetClientSentiment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientSentimentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GmailapiSvcServer).GetClientSentiment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gmailapi.GmailapiSvc/getClientSentiment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GmailapiSvcServer).GetClientSentiment(ctx, req.(*ClientSentimentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GmailapiSvc_OpenLightStreamerSubscription_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LightStreamerSubRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GmailapiSvcServer).OpenLightStreamerSubscription(m, &gmailapiSvcOpenLightStreamerSubscriptionServer{stream})
}

type GmailapiSvc_OpenLightStreamerSubscriptionServer interface {
	Send(*LightStreamerSubResponse) error
	grpc.ServerStream
}

type gmailapiSvcOpenLightStreamerSubscriptionServer struct {
	grpc.ServerStream
}

func (x *gmailapiSvcOpenLightStreamerSubscriptionServer) Send(m *LightStreamerSubResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _GmailapiSvc_MarketSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientSentimentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GmailapiSvcServer).MarketSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gmailapi.GmailapiSvc/marketSearch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GmailapiSvcServer).MarketSearch(ctx, req.(*ClientSentimentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GmailapiSvc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gmailapi.GmailapiSvc",
	HandlerType: (*GmailapiSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "subscribeToMail",
			Handler:    _GmailapiSvc_SubscribeToMail_Handler,
		},
		{
			MethodName: "openOTCOrder",
			Handler:    _GmailapiSvc_OpenOTCOrder_Handler,
		},
		{
			MethodName: "getConfirmationDetails",
			Handler:    _GmailapiSvc_GetConfirmationDetails_Handler,
		},
		{
			MethodName: "getClientSentiment",
			Handler:    _GmailapiSvc_GetClientSentiment_Handler,
		},
		{
			MethodName: "marketSearch",
			Handler:    _GmailapiSvc_MarketSearch_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "openLightStreamerSubscription",
			Handler:       _GmailapiSvc_OpenLightStreamerSubscription_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protos/gmailapi/gmailapi.proto",
}
